export { default as MenuIcon } from './menu-icon';
export { default as ArrowIcon } from './flecha-icon';
export { default as ArrowIcon1} from './flecha-two-icon';
export { default as ArrowIcon2} from './flecha-two-r';
export { default as ArrowIconR} from './flecha-icon-r';
export { default as RoundIcon} from './Round-icon';
export {default as QRicon} from './QR-icon';
export {default as CardIcon} from './Card-credit';
export {default as MoneyIcon} from './Money-icon';
export {default as Check} from './Check';